import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UiProvider from "./UiProvider";
import AppHeader from "@/components/AppHeader";
import { Toolbar } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <UiProvider>
          <AppHeader/>
          <Toolbar/>
        {children}
        </UiProvider>
        </div>
        </body>
    </html>
  );
}
